language: python
python:
- '3.7.9'
cache: pip
services: xvfb
addons:
  apt:
    update: true
    packages:
    - freeglut3-dev
    - python3-gi
    - python3-gi-cairo
install:
- pip install -r requirements-dev.txt
- pip install -e .
script:
- pytest --cov=dnk --cov-report term-missing
after_success:
- coveralls
