SCREEN_TITLE = "Drugs'n'Kebab"

SPRITE_SCALING = 4

ORIGINAL_SPRITE_WIDTH = 16
ORIGINAL_SPRITE_HEIGHT = 20

SPRITE_WIDTH = ORIGINAL_SPRITE_WIDTH * SPRITE_SCALING
SPRITE_HEIGHT = ORIGINAL_SPRITE_HEIGHT * SPRITE_SCALING

SCREEN_WIDTH = 10 * SPRITE_WIDTH
SCREEN_HEIGHT = 10 * SPRITE_HEIGHT

MOVEMENT_ANIMATION_DURATION = 0.5
