SCREEN_TITLE = "Drugs'n'Kebab"

SPRITE_SCALING = 4

ORIGINAL_SPRITE_WIDTH = 16
ORIGINAL_SPRITE_HEIGHT = 16

ORIGINAL_CHARACTER_SPRITE_HEIGHT = 20

SPRITE_WIDTH = ORIGINAL_SPRITE_WIDTH * SPRITE_SCALING
SPRITE_HEIGHT = ORIGINAL_SPRITE_HEIGHT * SPRITE_SCALING


CHARACTER_SPRITE_HEIGHT = ORIGINAL_CHARACTER_SPRITE_HEIGHT * SPRITE_SCALING

MAX_SPRITE_HEIGHT = SPRITE_HEIGHT

NB_TILES_WIDTH = 20
NB_TILES_HEIGHT = 20

SCREEN_WIDTH = NB_TILES_WIDTH * SPRITE_WIDTH
SCREEN_HEIGHT = NB_TILES_HEIGHT * MAX_SPRITE_HEIGHT

MOVEMENT_ANIMATION_DURATION = 0.5
