SCREEN_TITLE = "Drugs'n'Kebab"

FONTS = ("calibri", "arial")
FONT_SIZE = 16

DEBUG_MODE = False

SPRITE_SCALING = 4

ORIGINAL_SPRITE_WIDTH = 16
ORIGINAL_SPRITE_HEIGHT = 16

ORIGINAL_CHARACTER_SPRITE_HEIGHT = 20

SPRITE_WIDTH = ORIGINAL_SPRITE_WIDTH * SPRITE_SCALING
SPRITE_HEIGHT = ORIGINAL_SPRITE_HEIGHT * SPRITE_SCALING


CHARACTER_SPRITE_HEIGHT = ORIGINAL_CHARACTER_SPRITE_HEIGHT * SPRITE_SCALING


MAX_TILES_WIDTH = 20
MAX_TILES_HEIGHT = 20

MIN_TILES_WIDTH = 10
MIN_TILES_HEIGHT = 10

SCREEN_WIDTH = MAX_TILES_WIDTH * SPRITE_WIDTH
SCREEN_HEIGHT = MAX_TILES_HEIGHT * SPRITE_HEIGHT

MOVEMENT_ANIMATION_DURATION = 0.5

PREPARATION_TIME_UNIT = 0.5

ORDER_FREQUENCY = 2.5
FIRST_ORDER_DELAY = 3 * ORDER_FREQUENCY

NOTIFICATION_ANIMATION_DURATION = 0.2
NOTIFICATION_WAITING_DURATION = 0.3
NOTIFICATION_ALPHA = 100


WIDGET_BACKGROUND_COLOR = (255, 255, 255)
WIDGET_FRAME_COLOR = (0, 0, 0)
WIDGET_FRAME_SIZE = 10
WIDGET_WIDTH = (MIN_TILES_WIDTH * SPRITE_WIDTH) // 2
WIDGET_HEIGHT = (MIN_TILES_HEIGHT * SPRITE_HEIGHT) // 2

SELECTION_COLOR = (150, 150, 150)
